ALTER TABLE projects ADD COLUMN IF NOT EXISTS ux_experience TEXT NOT NULL DEFAULT '';
ALTER TABLE projects ADD COLUMN IF NOT EXISTS ux_design TEXT NOT NULL DEFAULT '';
ALTER TABLE projects ADD COLUMN IF NOT EXISTS ux_goal TEXT NOT NULL DEFAULT '';
ALTER TABLE projects ADD COLUMN IF NOT EXISTS ux_goal_revision INTEGER NOT NULL DEFAULT 0;
