ALTER TABLE domains ADD COLUMN IF NOT EXISTS definition_kind TEXT;
ALTER TABLE domains ADD COLUMN IF NOT EXISTS definition_value TEXT NOT NULL DEFAULT '';
ALTER TABLE domains ADD COLUMN IF NOT EXISTS definition_scene_ids JSONB NOT NULL DEFAULT '[]';
ALTER TABLE domains ADD COLUMN IF NOT EXISTS definition_revision INTEGER NOT NULL DEFAULT 0;
